server:
  port: 8080
spring:
  profiles:
    include: key
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: trace


