server:
  port: 8080
spring:
  profiles:
    include: config
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  #JPA Setting
  jpa:
    show-sql: true #if true, Show DB processing
    hibernate:
      ddl-auto: update  #DDL
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
    defer-datasource-initialization: true
sql:
  init:
    mode: always
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: off
